# Generated by Django 4.0.2 on 2022-06-22 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTraning',
            fields=[
                ('date', models.DateTimeField()),
                ('tranings_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text1', models.CharField(max_length=100)),
                ('question_text2', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date_publised')),
            ],
        ),
        migrations.CreateModel(
            name='Bars',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DK_test_server.datetraning')),
                ('bars1', models.PositiveSmallIntegerField(default=0)),
                ('bars2', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DK_test_server.datetraning')),
                ('entrance1', models.PositiveSmallIntegerField(default=0)),
                ('entrance2', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jumping',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DK_test_server.datetraning')),
                ('jumping1', models.PositiveSmallIntegerField(default=0)),
                ('jumping2', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DK_test_server.datetraning')),
                ('press1', models.PositiveSmallIntegerField(default=0)),
                ('press2', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DK_test_server.datetraning')),
                ('pull1', models.PositiveSmallIntegerField(default=0)),
                ('pull2', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DK_test_server.datetraning')),
                ('push1', models.PositiveSmallIntegerField(default=0)),
                ('push2', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sit',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DK_test_server.datetraning')),
                ('sit1', models.PositiveSmallIntegerField(default=0)),
                ('sit2', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DK_test_server.datetraning')),
                ('stadium1', models.PositiveSmallIntegerField(default=0)),
                ('stadium2', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DK_test_server.datetraning')),
                ('weight1', models.PositiveSmallIntegerField(default=0)),
                ('weight2', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weightcategory',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DK_test_server.datetraning')),
                ('weightcategory1', models.PositiveSmallIntegerField(default=0)),
                ('weightcategory2', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
