# Generated by Django 4.0.2 on 2022-07-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DK_test_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetraning',
            name='tranings_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
